databases:
  - name: belen-resplandor-de-luz-db
    plan: free
    databaseName: belen_store
    user: belen_store

services:
  - type: web
    name: belen-resplandor-de-luz
    runtime: node
    plan: starter
    buildCommand: npm install && npx prisma generate && npx prisma db push && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: DATABASE_URL
        fromDatabase:
          name: belen-resplandor-de-luz-db
          property: connectionString
      - key: NEXT_PUBLIC_SITE_URL
        sync: false
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: WOMPI_PUBLIC_KEY
        sync: false
      - key: WOMPI_INTEGRITY_SECRET
        sync: false
      - key: WOMPI_EVENTS_SECRET
        sync: false
      - key: MERCADOPAGO_ACCESS_TOKEN
        sync: false
